CloudERP/Controllers/Sale/Cart/SaleCartController.cs
using Domain.Models;
using Domain.UtilsAccess;
using Microsoft.AspNetCore.Mvc;
using Localization.CloudERP.Messages;

namespace CloudERP.Controllers.Sale.Cart
{
    public class SaleCartController : Controller
    {
        private readonly ISessionHelper _sessionHelper;
        private readonly IHttpClientHelper _httpClient;

        public SaleCartController(
            ISessionHelper sessionHelper,
            IHttpClientHelper httpClient)
        {
            _sessionHelper = sessionHelper ?? throw new ArgumentNullException(nameof(sessionHelper));
            _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        }

        // GET: SaleCart/NewSale
        public async Task<ActionResult> NewSale()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var findDetail = await _httpClient.GetAsync<IEnumerable<SaleCartDetail>>(
                    $"salecartapi/getsalecartdetails" +
                    $"?branchId={_sessionHelper.BranchID}&companyId={_sessionHelper.CompanyID}&userId={_sessionHelper.UserID}");

                ViewBag.TotalAmount = findDetail?.Sum(item => item.SaleQuantity * item.SaleUnitPrice);
                ViewBag.Products = await _httpClient.GetAsync<List<Domain.Models.Stock>>(
                    $"stockapi/getall?companyId={_sessionHelper.CompanyID}&branchId={_sessionHelper.BranchID}");

                return View(findDetail);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        public async Task<IActionResult> GetProductDetails(int id)
        {
            try
            {
                var product = await _httpClient.GetAsync<Domain.Models.Stock>(
                    $"salecartapi/getproductdetails?id={id}");

                return Json(new { data = product?.SaleUnitPrice });
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return Json(new { error = "Product details fetching error" });
            }
        }

        // POST: SaleCart/AddItem
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddItem(int PID, int Qty, float Price)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var checkQty = await _httpClient.GetAsync<Domain.Models.Stock>($"stockapi/getbyid?id={PID}");

                if (Qty > checkQty?.Quantity)
                {
                    ViewBag.Message = Messages.SaleQuantityError;
                    return RedirectToAction("NewSale");
                }

                var newItem = new SaleCartDetail()
                {
                    ProductID = PID,
                    SaleQuantity = Qty,
                    SaleUnitPrice = Price,
                    BranchID = _sessionHelper.BranchID,
                    CompanyID = _sessionHelper.CompanyID,
                    UserID = _sessionHelper.UserID
                };

                await _httpClient.PostAsync("salecartapi/additem", newItem);

                return RedirectToAction("NewSale");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        // POST: SaleCart/DeleteConfirm
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var success = await _httpClient.DeleteAsync($"salecartapi/deleteitem?id={id}");
                if (success) ViewBag.ErrorMessage = Messages.DeletedSuccessfully;
                else ViewBag.ErrorMessage = Messages.UnexpectedErrorMessage;

                return RedirectToAction("NewSale");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        public async Task<ActionResult> SelectCustomer()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                return View(await _httpClient.GetAsync<IEnumerable<Customer>>(
                    $"customerapi/getbysetting?branchId={_sessionHelper.BranchID}&companyId={_sessionHelper.CompanyID}"));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("NewPurchase");
            }
        }

        // POST: SaleCart/CancelSale
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CancelSale()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var responseMessage = await _httpClient.PostAsync(
                    $"salecartapi/cancelsale" +
                    $"?branchId={_sessionHelper.BranchID}&companyId={_sessionHelper.CompanyID}&userId={_sessionHelper.UserID}",
                    new { });

                ViewBag.Message = responseMessage;

                return RedirectToAction("NewSale");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        // POST: SaleCart/SaleConfirm
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaleConfirm(SaleConfirm saleConfirmDto)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                saleConfirmDto.CompanyID = _sessionHelper.CompanyID;
                saleConfirmDto.BranchID = _sessionHelper.BranchID;
                saleConfirmDto.UserID = _sessionHelper.UserID;

                var result = await _httpClient.PostAndReturnAsync<Dictionary<string, int>>(
                    "salecartapi/confirmsale", saleConfirmDto);

                if (result != null && result.TryGetValue("invoiceId", out int invoiceId) && invoiceId > 0)
                {
                    return RedirectToAction("PrintSaleInvoice", "SalePayment", new { id = invoiceId });
                }

                ViewBag.ErrorMessage = Messages.UnexpectedErrorMessage;
                return RedirectToAction("NewSale");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }
    }
}

CloudERP/Views/SaleCart/NewSale.cshtml
@model IEnumerable<Domain.Models.SaleCartDetail>
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Localization.CloudERP.Modules.Sale
@using Localization.CloudERP.Modules.Miscellaneous
@using Localization.CloudERP.Common
@{
    ViewBag.Title = Sale.NewSale;
    var products = ViewBag.Products as IEnumerable<Domain.Models.Stock>;
}

<!-- Tables Sorting-->
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<link href="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.css" rel="stylesheet">
<script src="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.js"></script>

<style>
    #dataTable_filter input[type="search"] {
        width: 15rem;
    }
</style>

@using (Html.BeginForm("AddItem", "SaleCart", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.ErrorMessage</h5>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">@Html.Raw(Sale.SelectProduct)</label>
            <div class="col-md-5">
                <select class="form-control" id="PID" name="PID" required>
                    <option value="">@Sale.SelectProduct</option>
                    @foreach (var product in products)
                    {
                        <option value="@product.ProductID">@product.ProductName (QTY: @product.Quantity)</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@Html.Raw(Sale.Quantity)</label>
            <div class="col-md-5">
                <input type="number" class="form-control" id="Qty" name="Qty" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@Html.Raw(Sale.UnitPrice)</label>
            <div class="col-md-5">
                <input type="number" class="form-control" id="Price" step=".01" name="Price" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@Html.Raw(Miscellaneous.ItemCost)</label>
            <div class="col-md-5">
                <input type="text" readonly class="form-control" id="selectItemCost" name="selectItemCost" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Sale.AddItem" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="card card-default col-md-12">
    <div class="card-header">
        <h3 class="text-bold">@Html.Raw(Sale.SaleItemsList)</h3>
        <h4 class="text-success">
            @{if (ViewBag.Message != null)
                {
                    @ViewBag.Message;
                }
                else
                {
                    @HttpContextAccessor.HttpContext?.Session.GetString("ErrorMessageSale");
                }
            }
        </h4>
    </div>
    <div class="card-body">
        <div class="table-responsive bootgrid">
            <table class="table table-striped table-hover" id="dataTable">
                <thead style="background-color:lightgray;">
                    <tr>
                        <th>
                            @Html.Raw(Miscellaneous.Items)
                        </th>
                        <th>
                            @Html.Raw(Sale.Quantity)
                        </th>
                        <th>
                            @Html.Raw(Sale.UnitPrice)
                        </th>
                        <th>
                            @Html.Raw(Miscellaneous.ItemCost)
                        </th>
                        <th>
                            @Html.Raw(Sale.User)
                        </th>
                        <th>
                            @Html.Raw(Common.Delete)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                            <td>@Html.DisplayFor(modelItem => item.SaleQuantity)</td>
                            <td>@Html.DisplayFor(modelItem => item.SaleUnitPrice)</td>
                            <td>@(string.Format("{0:0.000}", Math.Truncate(item.SaleQuantity * item.SaleUnitPrice * 10) / 10))</td>
                            <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                            <td>
                                @using (Html.BeginForm("DeleteConfirm", "SaleCart", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.Hidden("id", item.SaleCartDetailID)
                                    <input type="submit" value="@Common.Delete" class="btn btn-danger" />
                                }
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="background-color:black; color:white;">@Html.Raw(Sale.TotalSaleAmount)</td>
                        <td style="background-color:black; color:white;">
                            @(string.Format("{0:0.000}", Math.Truncate(ViewBag.TotalAmount * 10) / 10)) @Common.UAH
                        </td>
                    </tr>
                </tfoot>
            </table>
            <div style="float:right; margin-top:20px;" class="btn-group">
                <a href="@Url.Action("SelectCustomer")" class="btn btn-success" style="padding: 20px;">
                    @Sale.Next
                </a>
                @using (Html.BeginForm("CancelSale", "SaleCart", FormMethod.Post, new { @class = "form-inline" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger" style="padding:20px;">
                        @Sale.Cancel
                    </button>
                }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "columnDefs": [{ "orderable": false, "targets": 5 }],
            "lengthMenu": [[5, 10, 25, 50, 75, 100, 150, 200, -1], [5, 10, 25, 50, 75, 100, 150, 200, "All"]],
        });

        $("#PID").change(function () {
            $("#Price").val("0");
            $.ajax({
                url: '@Url.Action("GetProductDetails", "SaleCart")',
                type: 'GET',
                data: { id: $(this).val() },
                dataType: 'Json',
                success: function (response) {
                    $('#Price').val(response.data);
                },
                error: function () {
                    $('#Price').val("0");
                }
            });
        });

        $("#Qty, #Price").on("input", function () {
            var unitPrice = parseFloat($("#Price").val()) || 0;
            var qty = parseFloat($("#Qty").val()) || 0;
            $("#selectItemCost").val((unitPrice * qty).toFixed(2));
        });
    });
</script>

CloudERP/Views/SaleCart/SelectCustomer.cshtml
@model IEnumerable<Domain.Models.Customer>
@using Localization.CloudERP.Modules.Sale;
@using Localization.CloudERP.Modules.Miscellaneous;
@using Localization.CloudERP.Common;
@{
    ViewBag.Title = Sale.Finilize;
}

<!-- Tables Sorting-->
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<link href="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.css" rel="stylesheet">
<script src="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.js"></script>

<style>
    #dataTable_filter input[type="search"] {
        width: 15rem;
    }
</style>

@using (Html.BeginForm("SaleConfirm", "SaleCart", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Html.Raw(Sale.SaleDetails)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.ErrorMessage</h5>

        <!-- Description -->
        <div class="form-group">
            <label class="control-label col-md-2">@Html.Raw(Sale.SaleDescription)</label>
            <div class="col-md-12">
                <input type="text" class="form-control" id="Description" name="Description" required />
            </div>
        </div>

        <!-- IsPayment -->
        <div class="form-group">
            <label class="control-label col-md-4">@Html.Raw(Sale.IsSalePaymentPaid)</label>
            <div class="col-md-12">
                <input type="checkbox" name="IsPayment" />
            </div>
        </div>

        <input type="hidden" id="CustomerID" name="CustomerID" value="" />

        <div class="card card-default col-md-12">
            <div class="card-header">
                <input type="submit" style="float:right;" value="@Sale.FinilizeSale" class="btn btn-success" />
            </div>
            <div class="card-body">
                <div class="table-responsive bootgrid">
                    <table class="table table-striped table-hover" id="dataTable">
                        <thead style="background-color:lightgray;">
                            <tr>
                                <th>@Html.Raw(Miscellaneous.CustomerFullName)</th>
                                <th>@Html.Raw(Localization.CloudERP.Modules.User.User.ContactNo)</th>
                                <th>@Html.Raw(Localization.CloudERP.Modules.Supplier.Supplier.Address)</th>
                                <th>@Html.Raw(Common.Actions)</th>
                            </tr>
                        </thead>
                        <tbody id="customerList">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Customername)</td>
                                    <td>@Html.DisplayFor(modelItem => item.CustomerContact)</td>
                                    <td>@Html.DisplayFor(modelItem => item.CustomerAddress)</td>
                                    <td>
                                        <input type="checkbox" class="customer-checkbox" value="@item.CustomerID" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "columnDefs": [{ "orderable": false, "targets": 3 }],
            "lengthMenu": [[5, 10, 25, 50, 75, 100, 150, 200, -1], [5, 10, 25, 50, 75, 100, 150, 200, "All"]],
        });

        $('.customer-checkbox').on('change', function () {
            $('.customer-checkbox').not(this).prop('checked', false);

            if ($(this).is(':checked')) {
                $('#CustomerID').val($(this).val());
            } else {
                $('#CustomerID').val('');
            }
        });
    });
</script>