CloudERP/Controllers/Account/AccountHeadController.cs
using Domain.Models;
using Domain.UtilsAccess;
using Microsoft.AspNetCore.Mvc;
using Localization.CloudERP.Messages;

namespace CloudERP.Controllers.Account
{
    public class AccountHeadController : Controller
    {
        private readonly IHttpClientHelper _httpClient;
        private readonly ISessionHelper _sessionHelper;

        public AccountHeadController(
            ISessionHelper sessionHelper,
            IHttpClientHelper httpClient)
        {
            _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
            _sessionHelper = sessionHelper ?? throw new ArgumentNullException(nameof(sessionHelper));
        }

        public async Task<ActionResult> Index()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var accountHeads = await _httpClient.GetAsync<IEnumerable<AccountHead>>("accountheadapi/getall");
                return View(accountHeads);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult Create()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            return View(new AccountHead());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AccountHead model)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            model.UserID = _sessionHelper.UserID;

            if (!ModelState.IsValid) return View(model);

            try
            {
                var success = await _httpClient.PostAsync("accountheadapi/create", model);
                if (success) return RedirectToAction("Index");
                else ViewBag.ErrorMessage = Messages.AlreadyExists;

                return View(model);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var accountHead = await _httpClient.GetAsync<AccountHead>($"accountheadapi/getbyid?id={id}");
                if (accountHead == null) return NotFound();

                return View(accountHead);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AccountHead model)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            model.UserID = _sessionHelper.UserID;

            if (!ModelState.IsValid) return View(model);

            try
            {
                var success = await _httpClient.PutAsync($"accountheadapi/update?id={model.AccountHeadID}", model);
                if (success) return RedirectToAction("Index");
                else ViewBag.ErrorMessage = Messages.AlreadyExists;

                return View(model);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

CloudERP/Views/AccountHead/Create.cshtml
@model Domain.Models.AccountHead
@using Localization.CloudERP.Modules.Account
@using Localization.CloudERP.Common
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewBag.Title = Account.NewAccountHead;
}

<script>
    window.Culture = '@HttpContextAccessor.HttpContext?.Session.GetString("Culture")';
</script>

<script src="~/js/CustomScripts/VoiceRecognition.js"></script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.ErrorMessage</h5>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountHeadName, Account.AccountHeadTitle, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.AccountHeadName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountHeadName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, Account.HeadCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Common.Save" class="btn btn-success" />
                @Html.ActionLink(Common.BackToList, "Index", null, new { @class = "btn btn-default" })
                <button id="voiceRecognitionButton" class="btn btn-link" type="button">
                    <i class="fas fa-microphone" style="font-size: 1.5em; color: gray;"></i>
                </button>
            </div>
        </div>
    </div>
}

CloudERP/Views/AccountHead/Edit.cshtml
@model Domain.Models.AccountHead
@using Localization.CloudERP.Modules.Account
@using Localization.CloudERP.Common
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewBag.Title = Account.EditAccountHead;
}

<script>
    window.Culture = '@HttpContextAccessor.HttpContext?.Session.GetString("Culture")';
</script>

<script src="~/js/CustomScripts/VoiceRecognition.js"></script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.ErrorMessage</h5>

        @Html.HiddenFor(model => model.AccountHeadID)
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.AccountHeadName, Account.AccountHeadTitle, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.AccountHeadName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountHeadName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, Account.HeadCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Common.Save" class="btn btn-success" />
                @Html.ActionLink(Common.BackToList, "Index", null, new { @class = "btn btn-default" })
                <button id="voiceRecognitionButton" class="btn btn-link" type="button">
                    <i class="fas fa-microphone" style="font-size: 1.5em; color: gray;"></i>
                </button>
            </div>
        </div>
    </div>
}

CloudERP/Views/AccountHead/Index.cshtml
@model IEnumerable<Domain.Models.AccountHead>
@using Localization.CloudERP.Modules.Account
@using Localization.CloudERP.Common
@{
    ViewBag.Title = Account.AllAccountHeads;
}

<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>

<style>
    #dataTable_filter input[type="search"] {
        width: 15rem;
    }
</style>

<div class="card card-default col-md-12">
    <div class="card-header">
        @Html.ActionLink(Account.AddAccountHead, "Create", "AccountHead", null, new { @style = "float:left;", @class = "btn btn-success" })
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.ErrorMessage</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive bootgrid">
            <table class="table table-striped table-bordered table-hover" id="dataTable">
                <thead>
                    <tr>
                        <th>
                            @Html.Raw(Account.AccountHeadTitle)
                        </th>
                        <th>
                            @Html.Raw(Account.Code)
                        </th>
                        <th>
                            @Html.Raw(Localization.CloudERP.Modules.User.User.FullName)
                        </th>
                        <th>
                            @Html.Raw(Common.Actions)
                        </th>
                    </tr>
                </thead>
                <tbody id="list">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.AccountHeadName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FullName)
                            </td>
                            <td class="d-flex btn-group">
                                @Html.ActionLink(Common.Edit, "Edit", new { id = item.AccountHeadID }, new { @class = "btn btn-primary" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#dataTable').DataTable({
            layout: {
                topStart: {
                    buttons: [
                        { extend: 'copy', className: 'btn btn-secondary', exportOptions: { columns: ':not(:last-child)' } },
                        { extend: 'csv', className: 'btn btn-secondary', exportOptions: { columns: ':not(:last-child)' } },
                        { extend: 'excel', className: 'btn btn-secondary', exportOptions: { columns: ':not(:last-child)' } },
                        { extend: 'pdf', className: 'btn btn-secondary', exportOptions: { columns: ':not(:last-child)' } },
                        { extend: 'print', className: 'btn btn-secondary', exportOptions: { columns: ':not(:last-child)' } }
                    ]
                },
                topEnd: 'search',
                bottomStart: 'info',
                bottomEnd: 'paging',
                top2Start: 'pageLength'
            },
            lengthMenu: [[5, 10, 25, 50, 75, 100, 150, 200, -1], [5, 10, 25, 50, 75, 100, 150, 200, "*"]],
        });
    });
</script>