CloudERP/Controllers/Purchase/Cart/PurchaseCartController.cs
using Domain.Models;
using Domain.UtilsAccess;
using Localization.CloudERP.Messages;
using Microsoft.AspNetCore.Mvc;

namespace CloudERP.Controllers.Purchase.Cart
{
    public class PurchaseCartController : Controller
    {
        private readonly IHttpClientHelper _httpClient;
        private readonly ISessionHelper _sessionHelper;

        public PurchaseCartController(
            ISessionHelper sessionHelper,
            IHttpClientHelper httpClient)
        {
            _sessionHelper = sessionHelper ?? throw new ArgumentNullException(nameof(sessionHelper));
            _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        }

        public async Task<ActionResult> NewPurchase()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var details = await _httpClient.GetAsync<IEnumerable<PurchaseCartDetail>>(
                    $"purchasecartapi/getpurchasecartdetails?branchId={_sessionHelper.BranchID}&companyId={_sessionHelper.CompanyID}&userId={_sessionHelper.UserID}");

                ViewBag.TotalAmount = details?.Sum(item => item.PurchaseQuantity * item.PurchaseUnitPrice);
                ViewBag.Products = await _httpClient.GetAsync<IEnumerable<Domain.Models.Stock>>(
                    $"stockapi/getall?companyId={_sessionHelper.CompanyID}&branchId={_sessionHelper.BranchID}");

                return View(details);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        public async Task<IActionResult> GetProductDetails(int id)
        {
            try
            {
                var product = await _httpClient.GetAsync<Domain.Models.Stock>(
                    $"purchasecartapi/getproductdetails?id={id}");

                return Json(new { data = product?.CurrentPurchaseUnitPrice });
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddItem(int PID, int Qty, float Price)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var checkQty = await _httpClient.GetAsync<Domain.Models.Stock>($"stockapi/getbyid?id={PID}");

                if (Qty > checkQty?.Quantity)
                {
                    ViewBag.Message = Messages.SaleQuantityError;
                    return RedirectToAction("NewSale");
                }

                var newItem = new PurchaseCartDetail
                {
                    ProductID = PID,
                    PurchaseQuantity = Qty,
                    PurchaseUnitPrice = Price,
                    BranchID = _sessionHelper.BranchID,
                    CompanyID = _sessionHelper.CompanyID,
                    UserID = _sessionHelper.UserID
                };

                var success = await _httpClient.PostAsync("purchasecartapi/additem", newItem);
                if (success) ViewBag.ErrorMessage = Messages.ItemAddedSuccessfully;
                else ViewBag.ErrorMessage = Messages.AlreadyExists;

                return RedirectToAction("NewPurchase");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(int? id)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                var success = await _httpClient.DeleteAsync($"purchasecartapi/deleteitem?id={id}");
                if (success) ViewBag.ErrorMessage = Messages.DeletedSuccessfully;
                else ViewBag.ErrorMessage = Messages.UnexpectedErrorMessage;

                return RedirectToAction("NewPurchase");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        public async Task<ActionResult> SelectSupplier()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                return View(await _httpClient.GetAsync<IEnumerable<Supplier>>(
                    $"supplierapi/getbysetting?branchId={_sessionHelper.BranchID}&companyId={_sessionHelper.CompanyID}"));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CancelPurchase()
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                await _httpClient.PostAsync($"purchasecartapi/cancelpurchase", new
                {
                    branchId = _sessionHelper.BranchID,
                    companyId = _sessionHelper.CompanyID,
                    userId = _sessionHelper.UserID
                });

                return RedirectToAction("NewPurchase");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PurchaseConfirm(PurchaseConfirm purchaseConfirmDto)
        {
            if (!_sessionHelper.IsAuthenticated)
                return RedirectToAction("Login", "Home");

            try
            {
                purchaseConfirmDto.CompanyID = _sessionHelper.CompanyID;
                purchaseConfirmDto.BranchID = _sessionHelper.BranchID;
                purchaseConfirmDto.UserID = _sessionHelper.UserID;

                var result = await _httpClient.PostAndReturnAsync<Dictionary<string, int>>(
                    "purchasecartapi/confirmpurchase", purchaseConfirmDto);

                if (result != null && result.TryGetValue("invoiceId", out int invoiceId) && invoiceId > 0)
                {
                    return RedirectToAction("PrintPurchaseInvoice", "PurchasePayment", new { id = invoiceId });
                }

                ViewBag.ErrorMessage = Messages.UnexpectedErrorMessage;
                return RedirectToAction("NewPurchase");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = Messages.UnexpectedErrorMessage + ex.Message;
                return RedirectToAction("EP500", "EP");
            }
        }
    }
}

CloudERP/Views/PurchaseCart/NewPurchase.cshtml
@model IEnumerable<Domain.Models.PurchaseCartDetail>
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Localization.CloudERP.Modules.Purchase
@using Localization.CloudERP.Modules.Sale
@using Localization.CloudERP.Modules.Miscellaneous
@using Localization.CloudERP.Common
@{
    ViewBag.Title = Purchase.Purchasing;
    var products = ViewBag.Products as IEnumerable<Domain.Models.Stock>;
}

<!-- Tables Sorting-->
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<link href="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.css" rel="stylesheet">
<script src="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.js"></script>

<style>
    #dataTable_filter input[type="search"] {
        width: 15rem;
    }
</style>

@using (Html.BeginForm("AddItem", "PurchaseCart", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.ErrorMessage</h5>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">@Html.Raw(Sale.SelectProduct)</label>
            <div class="col-md-5">
                <select class="form-control" id="PID" name="PID" required>
                    <option value="">@Sale.SelectProduct</option>
                    @foreach (var product in products)
                    {
                        <option value="@product.ProductID">@product.ProductName (QTY: @product.Quantity)</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@Sale.Quantity</label>
            <div class="col-md-5">
                <input type="number" class="form-control" id="Qty" name="Qty" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@Purchase.UnitPrice</label>
            <div class="col-md-5">
                <input type="number" class="form-control" id="Price" step=".01" name="Price" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@Html.Raw(Miscellaneous.ItemCost)</label>
            <div class="col-md-5">
                <input type="text" readonly class="form-control" id="selectItemCost" name="selectItemCost" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Sale.AddItem" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="card card-default col-md-12">
    <div class="card-header">
        <h3 class="text-bold">@Purchase.ItemsList</h3>
        <h4 class="text-success">
            @{
                if (ViewBag.Message != null) 
                {
                    @ViewBag.Message;           
                } 
                else 
                {
                    @HttpContextAccessor.HttpContext?.Session.GetString("ErrorMessagePurchase");
                } 
            }
        </h4>
    </div>
    <div class="card-body">
        <div class="table-responsive bootgrid">
            <table class="table table-striped table-hover" id="dataTable">
                <thead style="background-color:lightgray;">
                    <tr>
                        <th>
                            @Miscellaneous.Items
                        </th>
                        <th>
                            @Sale.Quantity
                        </th>
                        <th>
                            @Purchase.UnitPrice
                        </th>
                        <th>
                            @Miscellaneous.ItemCost
                        </th>
                        <th>
                            @Localization.CloudERP.Modules.User.User.FullName
                        </th>
                        <th>
                            @Common.Actions
                        </th>
                    </tr>
                </thead>
                <tbody id="purchaseList">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                            <td>@Html.DisplayFor(modelItem => item.PurchaseQuantity)</td>
                            <td>@Html.DisplayFor(modelItem => item.PurchaseUnitPrice)</td>
                            <td>@(string.Format("{0:0.000}", Math.Truncate(item.PurchaseQuantity * item.PurchaseUnitPrice * 10) / 10))</td>
                            <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                            <td class="d-flex btn-group">
                                @using (Html.BeginForm("DeleteConfirm", "PurchaseCart", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.Hidden("id", item.PurchaseCartDetailID)
                                    <input type="submit" value="@Common.Delete" class="btn btn-danger" />
                                }
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="background-color:black; color:white;">@Purchase.TotalPurchaseAmount</td>
                        <td style="background-color:black; color:white;">
                            @(string.Format("{0:0.000}", Math.Truncate(ViewBag.TotalAmount * 10) / 10)) @Common.UAH
                        </td>
                    </tr>
                </tfoot>
            </table>
            <div style="float:right; margin-top:20px;" class="btn-group">
                <a href="@Url.Action("SelectSupplier")" class="btn btn-success" style="padding: 20px;">
                    @Sale.Next
                </a>
                @using (Html.BeginForm("CancelPurchase", "PurchaseCart", FormMethod.Post, new { @class = "form-inline" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger" style="padding:20px;">
                        @Sale.Cancel
                    </button>
                }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "columnDefs": [{ "orderable": false, "targets": 5 }],
            "lengthMenu": [[5, 10, 25, 50, 75, 100, 150, 200, -1], [5, 10, 25, 50, 75, 100, 150, 200, "All"]],
        });

        $('#PID').change(function () {
            var productId = $(this).val();
            if (productId) {
                $.ajax({
                    url: '@Url.Action("GetProductDetails", "PurchaseCart")',
                    type: 'GET',
                    data: { id: productId },
                    success: function (response) {
                        $('#Price').val(response.CurrentPurchaseUnitPrice);
                    },
                    error: function () {
                        alert('Error fetching product price');
                    }
                });
            } else {
                $('#Price').val('');
            }
        });

        $("#Qty, #Price").on("input", function () {
            var unitPrice = parseFloat($("#Price").val()) || 0;
            var qty = parseFloat($("#Qty").val()) || 0;
            $("#selectItemCost").val((unitPrice * qty).toFixed(2));
        });
    });
</script>

CloudERP/Views/PurchaseCart/SelectSupplier.cshtml
@model IEnumerable<Domain.Models.Supplier>
@using Localization.CloudERP.Modules.Purchase
@using Localization.CloudERP.Modules.Sale
@using Localization.CloudERP.Modules.Supplier
@using Localization.CloudERP.Modules.Miscellaneous
@using Localization.CloudERP.Common
@{
    ViewBag.Title = Sale.Finilize;
}

<!-- Tables Sorting-->
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<link href="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.css" rel="stylesheet">
<script src="https://cdn.datatables.net/v/bs5/dt-2.2.2/datatables.min.js"></script>

<style>
    #dataTable_filter input[type="search"] {
        width: 15rem;
    }
</style>

@using (Html.BeginForm("PurchaseConfirm", "PurchaseCart", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Purchase.PurchaseDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.ErrorMessage</h5>

        <div class="form-group">
            <label class="control-label col-md-2">@Purchase.PurchaseDescription</label>
            <div class="col-md-12">
                <input type="text" class="form-control" id="Description" name="Description" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-4">@Purchase.IsPurchasePaymentPaid</label>
            <div class="col-md-12">
                <input type="checkbox" name="IsPayment" />
            </div>
        </div>

        <input type="hidden" id="SupplierID" name="SupplierID" value="" />

        <div class="card card-default col-md-12">
            <div class="card-header">
                <input type="submit" style="float:right;" value="@Purchase.FinilizePurchasing" class="btn btn-success" />
            </div>
            <div class="card-body">
                <div class="table-responsive bootgrid">
                    <table class="table table-striped table-hover" id="dataTable">
                        <thead style="background-color:lightgray;">
                            <tr>
                                <th>@Supplier.SupplierName</th>
                                <th>@Supplier.ConatctNo</th>
                                <th>@Localization.CloudERP.Modules.User.User.EmailAddress</th>
                                <th>@Localization.CloudERP.Common.Common.Actions.ToString()</th>
                            </tr>
                        </thead>
                        <tbody id="supplierList">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.SupplierName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.SupplierConatctNo)</td>
                                    <td>@Html.DisplayFor(modelItem => item.SupplierEmail)</td>
                                    <td class="d-flex">
                                        <input type="checkbox" class="supplier-checkbox" value="@item.SupplierID" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "columnDefs": [{ "orderable": false, "targets": [1, 2] }],
            "lengthMenu": [[5, 10, 25, 50, 75, 100, 150, 200, -1], [5, 10, 25, 50, 75, 100, 150, 200, "All"]],
        });

        $('.supplier-checkbox').on('change', function () {
            $('.supplier-checkbox').not(this).prop('checked', false);

            if ($(this).is(':checked')) {
                $('#SupplierID').val($(this).val());
            } else {
                $('#SupplierID').val('');
            }
        });
    });
</script>